### ISSUE TITLE
Excuse me, why do you want to modify trust.ini and RKTRUST.ini

### ISSUE THREAD

**Issue by rainwonder** [jayanta525/rk3308-rock-pi-s#1]

**Comment by jayanta525** [comment]
Please provide some description regarding your issue.

**Comment by rainwonder** [comment]
I compile the uboot with rktools,but I
Can’t boot from norflash，can you give me some details .

**Comment by jayanta525** [comment]
Hello, the branch u-boot development was halted because RK3308 doesn't support mainline ATF. And I wasn't able to get SPL/TPL u-boot to boot in this board, as I need to do through tests and I don't have this board.

This OpenWrt repo uses mililoader blobs from armbian project instead.
