### ISSUE TITLE
bin ouptuts not factor

### ISSUE THREAD

**Issue by flatmax** [jayanta525/rk3308-rock-pi-s#2]
Hey there,

After building there aren't any factory images output, this is what I see :

```
$ ls bin/targets/rockchip/armv8/
config.buildinfo
feeds.buildinfo
openwrt-rockchip-armv8-radxa_rock-pi-s-ext4-sysupgrade.img.gz
openwrt-rockchip-armv8-radxa_rock-pi-s.manifest
openwrt-rockchip-armv8-radxa_rock-pi-s-squashfs-sysupgrade.img.gz
packages
sha256sums
version.buildinfo
```

Can I write the sysupgrade.img to sdcard for a first install ?
Should I enable a different build option to also output factory.img.gz or is it not necessary ?
What is the best way to write the sdcard using a gz file ?

**Comment by jayanta525** [comment]
@flatmax  Yes, you can use the sysupgrade image directly.
