### ISSUE TITLE
could you add kes nod for rock-pi-s-dts?

### ISSUE THREAD

**Issue by mercurydarkork** [jayanta525/rk3308-rock-pi-s#4]
I try to add power key and maskrom key  for rock-pi-s , but I can't ,could you help doing this?

**Comment by jayanta525** [comment]
@mercurydarkork sure. I will look into it.

**Comment by mercurydarkork** [comment]
thanks very much I am waiting for this.

**Comment by mercurydarkork** [comment]
the maskrom key's pin is 43 and the reset key's pin is 96 ,https://wiki.radxa.com/RockpiS/Core/Pinout. but I don't know how to use this clue.

**Comment by jayanta525** [comment]
@mercurydarkork I don't have the board, can you check if the reset key works on the Radxa provided debian/ubuntu/armbian?

**Comment by mercurydarkork** [comment]
ok I will check it

**Comment by jayanta525** [comment]
the key nodes can be added to the DTS with proper GPIO assignment.
