### ISSUE TITLE
Will there be wifi support ?

### ISSUE THREAD

**Issue by ilker-aktuna** [jayanta525/rk3308-rock-pi-s#7]
### Describe the bug

There is no wifi support at the moment. But will it be possible ?

### OpenWrt version

r0-865657c

### OpenWrt target/subtarget

rockchip/armv8

### Device

Radxa ROCK Pi S

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by jayanta525** [comment]
@ilker-aktuna 

Yes, there will be WiFi support once the kernel is upgraded to Linux v6.5.
