### ISSUE TITLE
Compilation and build rk3308-rock-pi-s with Erlang OTP 23

### ISSUE THREAD

**Issue by ottoTillsammans** [jayanta525/rk3308-rock-pi-s#8]
### Describe the bug

I want to build this project with Erlang OTP 24, but nothing yet. I tried using feeds with both git-src and custom options, but the output firmware doesn't contains working Erlang. If I manually replace the source archive and hash in the Makefile, the build fails with type 1 and type 2 errors (yes I know this is a bad idea). OTP 26 builds and works correctly, but it i can't build with it my project that contains nklib.

Can I get any advice on how to do this?

Thanks so much, Dmitry

### OpenWrt version

From rk3308-rock-pi-s repo

### OpenWrt target/subtarget

Rockchip

### Device

Media gateway on Rockchip (doesn't exist yet, in developing)

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by jayanta525** [comment]
@ottoTillsammans Is erlang package enabled in menuconfig?

**Comment by ottoTillsammans** [comment]
@jayanta525 Yes, Erlang package is enabled, but if I just switch it on in **menuconfig** without configuring in **feeds.conf** the manager installs the OTP 26 while I need OTP 24. When I disable Erlang in **menuconfig -> languages**, but add it in **feeds.conf** and then enable in **menuconfig -> feeds**, the OpenWrt builds successfully, but Erlang doesn't starts.

**Comment by ottoTillsammans** [comment]
@jayanta525 Small clarificationSmall clarification: I meant OTP 24, not OTP 23

**Comment by jayanta525** [comment]
@ottoTillsammans For the 24 version, you can refer to this https://github.com/openwrt/packages/commit/cca300147570d49c39eb6b9b3f52e69ec9836f91

You'll need to copy the patches accordingly.
